# contrib/ specific ruff linter overrides

# root linter settings are defined in the file below
extend = "../pyproject.toml"

extend-ignore = [
    # https://github.com/charliermarsh/ruff#flake8-type-checking-tch
    # This is likely to be a high-touch rule that most contribs don't need to care about.
    "TCH001",
]

[isort]
known-first-party = ["great_expectations", "tests"]
known-third-party = ["dataprofiler", "capitalone_dataprofiler_expectations"]
