repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
        exclude: docs/.*|tests/data_context/fixtures/bad_yml/great_expectations\.yml
      - id: end-of-file-fixer
        exclude: docs/.*|tests/test_sets/broken_excel_file\.xls|.*.ge_store_backend_id
      - id: trailing-whitespace
        exclude: docs/.*|tests/.*.fixture
      - id: requirements-txt-fixer
        exclude: docs/.*
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        files: ^(great_expectations/core)
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: ["--py3-plus"]
# https://pre-commit.ci/
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_branch: 'develop'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    # skip flake8 enforcement with pre-commit CI as it is enforced elsewhere
    # flake8 hook also doesn't have an options to auto-fix
    # pre-commit hooks should either have mechanisms for auto-fixing or should be simple to do manually
    skip: [flake8]
    submodules: false
