# This file is responsible for configuring the `dev` pipeline (https://dev.azure.com/great-expectations/great_expectations/_build)
#
# The pipeline is run under the following conditions:
#   - On the develop branch whenever a commit is made to an open PR
#
# `dev` runs unit tests for any directories that have sufficient coverage and integration tests for those that don't.
# The pipeline aims to balance both performance and safety to improve the developer experience but is innately less thorough than `great_expectations`.

trigger:
  branches:
    include:
    - pre_pr-* # Can be used to test both `great_expectations` and `dependency_graph` pipelines
    - develop
    exclude:
    - main

resources:
  containers:
  - container: postgres
    image: postgres:11
    ports:
    - 5432:5432
    env:
      POSTGRES_DB: "test_ci"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  - container: mysql
    image: mysql:8.0.20
    ports:
      - 3306:3306
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_ci
  - container: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    env:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ReallyStrongPwd1234%^&*
      MSSQL_DB: test_ci
      MSSQL_PID: Developer
    ports:
      - 1433:1433
  - container: trino
    image: trinodb/trino:379
    ports:
      - 8088:8080

variables:
  GE_USAGE_STATISTICS_URL: "https://qa.stats.greatexpectations.io/great_expectations/v1/usage_statistics"


stages:
  - stage: scope_check
    pool:
      vmImage: 'ubuntu-20.04'
    jobs:
      - job: changes
        steps:
          - task: ChangedFiles@1
            name: CheckChanges
            inputs:
              verbose: true
              rules: |
                [ContribChanged]
                contrib/**

                [ExperimentalChanged]
                contrib/experimental/**

                [DocsChanged]
                docs/**
                tests/integration/docusaurus/**
                tests/integration/fixtures/**
                tests/test_sets/**

                [GEChanged]
                great_expectations/**/*.py
                tests/**
                /*.txt
                /*.yml
                requirements*
                azure-pipelines*

  - stage: lint
    dependsOn: scope_check
    pool:
      vmImage: 'ubuntu-latest'

    jobs:
      - job: lint
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: 3.7
            displayName: 'Use Python 3.7'

          - script: |
              pip install isort[requirements]==5.10.1 flake8==5.0.4 black==22.3.0 pyupgrade==2.7.2 invoke==1.7.1
              EXIT_STATUS=0
              invoke fmt --check || EXIT_STATUS=$?
              invoke lint || EXIT_STATUS=$?
              pyupgrade --py3-plus || EXIT_STATUS=$?
              exit $EXIT_STATUS

  - stage: custom_checks
    dependsOn: scope_check
    pool:
      vmImage: 'ubuntu-latest'

    jobs:
    - job: type_hint_checker
      steps:
      - script: |
          pip install mypy invoke # Prereq for type hint script
          invoke type-coverage
        name: TypeHintChecker

    - job: static_type_check
      steps:
      - script: |
          pip install mypy invoke
          invoke type-check --install-types
        name: StaticTypeCheck

    - job: docstring_checker
      steps:
      - bash: python scripts/check_docstring_coverage.py
        name: DocstringChecker

    - job: unused_import_checker
      steps:
      - script: |
          pip install flake8
          # https://www.flake8rules.com/rules/F401.html
          flake8 --select F401 great_expectations tests
        name: UnusedImportChecker

  - stage: import_ge
    dependsOn: scope_check
    pool:
      vmImage: 'ubuntu-18.04'

    jobs:
      - job: import_ge

        steps:
         - task: UsePythonVersion@0
           inputs:
             versionSpec: '3.7'
           displayName: 'Use Python 3.7'

         - bash: python -m pip install --upgrade pip==21.3.1
           displayName: 'Update pip'

         - script: |
             pip install  .
           displayName: 'Install GE and required dependencies (i.e. not sqlalchemy)'

         - script: |
             python -c "import great_expectations as ge; print('Successfully imported GE Version:', ge.__version__)"
           displayName: 'Import Great Expectations'

  - stage: required
    dependsOn: [scope_check, lint, import_ge, custom_checks]
    pool:
      vmImage: 'ubuntu-18.04'

    jobs:
      # Runs pytest without any additional flags
      - job: minimal
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)
        strategy:
          # This matrix is intended to split up our sizeable test suite into two distinct components.
          # By splitting up slow tests from the remainder of the suite, we can parallelize test runs
          # at the cost of an additional Azure worker.
          #
          # To work as intended, "standard" and "slow" should be equally performant.
          matrix:
            standard:
              pytest_args: 'tests --ignore "tests/rule_based_profiler"'
            slow:
              pytest_args: 'tests/rule_based_profiler'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
            displayName: 'Use Python 3.7'

          - bash: python -m pip install --upgrade pip==21.3.1
            displayName: 'Update pip'

          - script: |
                pip install numpy
                pip install pandas
                pip install scipy
            displayName: 'Install numpy, pandas, and scipy'

          - script: |
              pip install --requirement requirements.txt
              echo "about to run pip install --requirement reqs/requirements-dev-test.txt --constraint constraints-dev.txt"
              pip install --requirement reqs/requirements-dev-test.txt --constraint constraints-dev.txt
              pip install  .
            displayName: 'Install dependencies'

          - script: |
              # Install dependencies
              pip install pytest-cov pytest-icdiff pytest-mock pytest-azurepipelines invoke

              # Run unit-tests
              invoke tests --ci --cloud --timeout=3.0

            displayName: 'Unit Tests'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

          - script: |
              # Run pytest
              pytest $(pytest_args) \
                --no-sqlalchemy \
                --ignore 'tests/cli' \
                --ignore 'contrib/cli/tests' \
                --ignore 'tests/integration/usage_statistics' \
                --napoleon-docstrings \
                --junitxml=junit/test-results.xml \
                --cov=. \
                --cov-report=xml \
                --cov-report=html \
                -m 'not unit and not e2e' \
                --durations=10

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-*.xml'
              testRunTitle: 'Publish test results for Python $(python.version)'

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

      # Runs pytest with Spark and Postgres enabled
      - job: comprehensive
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)
        strategy:
          # This matrix is intended to split up our sizeable test suite into two distinct components.
          # By splitting up slow tests from the remainder of the suite, we can parallelize test runs
          # at the cost of an additional Azure worker.
          #
          # To work as intended, "standard" and "slow" should be equally performant.
          matrix:
            standard:
              pytest_args: 'tests --ignore "tests/rule_based_profiler"'
            slow:
              pytest_args: 'tests/rule_based_profiler'

        services:
          postgres: postgres

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
            displayName: 'Use Python 3.7'

          - bash: python -m pip install --upgrade pip==21.3.1
            displayName: 'Update pip'

          - script: |
                pip install pandas
            displayName: 'Install pandas'

          - script: |
              pip install --requirement requirements.txt
              echo "about to run pip install --requirement requirements-dev.txt --constraint constraints-dev.txt"
              pip install --requirement requirements-dev.txt --constraint constraints-dev.txt
              pip install  .
            displayName: 'Install dependencies'

          - script: |
              pip install pytest-cov pytest-azurepipelines

              # Run pytest
              pytest $(pytest_args) \
                --postgresql \
                --spark \
                --ignore 'tests/cli' \
                --ignore 'contrib/cli/tests' \
                --ignore 'tests/integration/usage_statistics' \
                --napoleon-docstrings \
                --junitxml=junit/test-results.xml \
                --cov=. \
                --cov-report=xml \
                --cov-report=html \
                -m 'not e2e'

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-*.xml'
              testRunTitle: 'Publish test results for Python $(python.version)'

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - stage: usage_stats_integration
    dependsOn: [scope_check, lint, import_ge, custom_checks]
    pool:
      vmImage: 'ubuntu-latest'

    jobs:
      - job: test_usage_stats_messages
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)
        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==20.2.4
            displayName: 'Update pip'

          - script: |
              pip install --requirement reqs/requirements-dev-test.txt
              pip install --requirement requirements.txt
              pip install .
            displayName: 'Install dependencies'

          # Due to the relatively small number of usage_stats tests, we deem it appropriate to test them in their entirely through pytest
          - script: |
              pip install pytest-azurepipelines
              pytest --no-sqlalchemy --aws-integration -v tests/integration/usage_statistics

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

  - stage: db_integration
    pool:
      vmImage: 'ubuntu-latest'

    dependsOn: [scope_check, lint, import_ge, custom_checks]

    jobs:
      - job: mysql
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)

        services:
          mysql: mysql

        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==21.3.1
            displayName: 'Update pip'

          - script: |
              printf 'Waiting for MySQL database to accept connections'
              until mysql --host=localhost --protocol=TCP --port=3306 --user=root --password='' --execute "SHOW DATABASES"; do
                printf '.'
                sleep 1;
              done;
            displayName: Wait for database to initialise

          - script: |
              echo "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));" > mysql_setup_script.sql
              mysql --host=localhost --protocol=TCP --port=3306 --user=root --password='' --reconnect < mysql_setup_script.sql
            displayName: 'Configure mysql'

          - script: |
              pip install \
                --requirement reqs/requirements-dev-test.txt \
                --requirement reqs/requirements-dev-sqlalchemy.txt \
                --constraint constraints-dev.txt
              pip install --requirement requirements.txt
              pip install .
            displayName: 'Install dependencies'

          - script: |
              # Install dependencies
              pip install pytest-cov pytest-azurepipelines

              # Run pytest
              pytest tests/test_definitions tests/expectations \
                --mysql \
                --napoleon-docstrings \
                --junitxml=junit/test-results.xml \
                --cov=. \
                --cov-report=xml \
                --cov-report=html

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

      - job: mssql
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)

        services:
          mssql: mssql

        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==21.3.1
            displayName: 'Update pip'

          - script: |
              sqlcmd -U sa -P "ReallyStrongPwd1234%^&*" -Q "CREATE DATABASE test_ci;" -o create_db_output.txt

          - script: |
              pip install \
                --requirement reqs/requirements-dev-test.txt \
                --requirement reqs/requirements-dev-sqlalchemy.txt \
                --constraint constraints-dev.txt
              pip install --requirement requirements.txt
              pip install .
            displayName: 'Install dependencies'

          - script: |
              # Install dependencies
              pip install pytest-cov pytest-azurepipelines

              # Run pytest
              pytest tests/test_definitions tests/expectations \
                --mssql \
                --napoleon-docstrings \
                --junitxml=junit/test-results.xml \
                --cov=. \
                --cov-report=xml \
                --cov-report=html

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

      - job: trino
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)

        services:
          trino: trino

        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==21.3.1
            displayName: 'Update pip'

          - script: |
              printf 'Waiting for Trino database to accept connections'
              sleep 30
#             until trino --execute "SHOW CATALOGS"; do
#               printf '.'
#               sleep 1;
#             done;
            displayName: Wait for database to initialise

          - script: |
              pip install \
                --requirement reqs/requirements-dev-test.txt \
                --requirement reqs/requirements-dev-sqlalchemy.txt \
                --constraint constraints-dev.txt
              pip install --requirement requirements.txt
              pip install .
            displayName: 'Install dependencies'

          - script: |
              # Install dependencies
              pip install pytest-cov pytest-azurepipelines

              # Run pytest
              pytest tests/test_definitions tests/expectations \
                --trino \
                --napoleon-docstrings \
                --junitxml=junit/test-results.xml \
                --cov=. \
                --cov-report=xml \
                --cov-report=html

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}

  - stage: cli_integration
    dependsOn: [scope_check, lint, import_ge, custom_checks]
    pool:
      vmImage: 'ubuntu-latest'

    jobs:
      - job: test_cli
        condition: eq(stageDependencies.scope_check.changes.outputs['CheckChanges.GEChanged'], true)

        services:
          postgres: postgres

        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==21.3.1
            displayName: 'Update pip'

          - script: |
              pip install \
                --requirement reqs/requirements-dev-test.txt \
                --requirement reqs/requirements-dev-spark.txt \
                --requirement reqs/requirements-dev-sqlalchemy.txt \
                --constraint constraints-dev.txt
              pip install --requirement requirements.txt
              pip install .
            displayName: 'Install dependencies'

          - script: |
              # Run pytest
              pytest --postgresql --spark --aws-integration tests/cli

            displayName: 'pytest'
            env:
              GE_USAGE_STATISTICS_URL: ${{ variables.GE_USAGE_STATISTICS_URL }}
